config/routes.rb
Markus::Application.routes.draw do
  # Install the default routes as the lowest priority.
  root :controller => "main", :action => "login"

  # optional path scope (denoted by the parentheses)
  scope "(:locale)", :locale => /en|fr|pt/  do
    # API routes
    namespace :api do
      resources :users, :except => [:new, :edit]
      resources :assignments, :except => [:new, :edit] do
        resources :groups, :except => [:new, :edit] do
          resources :submission_downloads, :except => [:new, :edit]
          resources :test_results, :except => [:new, :edit]
        end
      end
      resources :main_api
    end

    resources :admins do
      collection do
        post 'populate'
      end
    end

    resources :assignments do

      collection do
        get 'download_csv_grades_report'
        post 'update_group_properties_on_persist'
        get 'delete_rejected'
        post 'update_collected_submissions'
        get 'download_assignment_list'
        post 'upload_assignment_list'
      end

      member do
        get 'refresh_graph'
        get 'student_interface'
        get 'update_group_properties_on_persist'
        post 'invite_member'
        get 'creategroup'
        get 'join_group'
        get 'deletegroup'
        get 'decline_invitation'
        post 'disinvite_member'
        get 'render_test_result'
      end

      resources :rubrics do
        member do
          delete 'destroy'
          get 'move_criterion'
        end

        collection do
          post 'update_positions'
          post 'csv_upload'
          post 'yml_upload'
          get 'download_csv'
          get 'download_yml'
        end
      end

      resources :flexible_criteria do
        member do
          delete 'destroy'
          get 'move_criterion'
        end

        collection do
          post 'upload'
          post 'update_positions'
          get 'download'
        end
      end

      resources :automated_tests do
        collection do
          get 'manage'
          post 'update' # because of collection
          post 'update_positions'
          get 'update_positions'
          post 'upload'
          get 'download'
          get 'move_criterion'
        end
      end

      resources :groups do

        member do
          post 'rename_group'
          get 'rename_group_dialog'
        end

        collection do
          post 'populate'
          post 'populate_students'
          get 'add_group'
          get 'use_another_assignment_groups'
          get 'manage'
          post 'csv_upload'
          get 'add_csv_group'
          get 'download_grouplist'
          get 'create_groups_when_students_work_alone'
          get 'valid_grouping'
          get 'invalid_grouping'
          get 'global_actions'
          get 'rename_group'
          delete 'remove_group'
          post 'add_group'
          post 'global_actions'
        end
      end

      resources :submissions do
        collection do
          get 'file_manager'
          get 'browse'
          post 'populate_file_manager'
          get 'collect_all_submissions'
          get 'download_simple_csv_report'
          get 'download_detailed_csv_report'
          get 'download_svn_export_list'
          get 'download_svn_export_commands'
          get 'download_svn_repo_list'
          get 'collect_ta_submissions'
          post 'update_submissions'
          post 'populate_repo_browser'
          post 'update_converted_pdfs'
          get 'updated_files'
          get 'replace_files'
          get 'delete_files'
          post 'update_files'
          post 'server_time'
          get 'download'
          get 'download_groupings_files'
        end

        member do
          get 'collect_and_begin_grading'
          post 'manually_collect_and_begin_grading'
          get 'repo_browser'
          post 'repo_browser'
          get 'downloads'
        end

        resources :results do
          collection do
            post 'update_mark'
            get 'expand_criteria'
            get 'collapse_criteria'
            get 'expand_unmarked_criteria'
            get 'edit'
            get 'download'
          end

          member do
            get 'add_extra_marks'
            get 'add_extra_mark'
            get 'download'
            post 'download'
            get 'download_zip'
            get 'cancel_remark_request'
            get 'codeviewer'
            post 'codeviewer'
            get 'expand_criteria'
            get 'collapse_criteria'
            post 'add_extra_mark'
            post 'delete_grace_period_deduction'
            get 'next_grouping'
            post 'remove_extra_mark'
            get 'expand_unmarked_criteria'
            post 'set_released_to_students'
            put 'update_overall_comment'
            post 'update_overall_remark_comment'
            post 'update_marking_state'
            get 'update_remark_request'
            get 'update_positions'
            post 'update_mark'
            get 'view_marks'
          end
        end
      end

      resources :graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_groupings_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

      resources :annotation_categories do
        member do
          get 'get_annotations'
          delete 'delete_annotation_category'
          delete 'delete_annotation_text'
          get 'add_annotation_text'
          post 'add_annotation_text'
          put 'update_annotation'
        end

        collection do
          get 'add_annotation_category'
          post 'csv_upload'
          get 'delete_annotation_category'
          get 'download'
          post 'yml_upload'
          post 'add_annotation_category'
          post 'update_annotation_category'
          get 'add_annotation_text'
          post 'delete_annotation_text'
          post 'update_annotation'
        end
      end
    end

    resources :grade_entry_forms do
      collection do
        get 'student_interface'
      end

      member do
        get 'grades'
        get 'g_table_paginate'
        post 'g_table_paginate'
        get 'csv_download'
        post 'csv_upload'
        post 'update_grade'
        post 'update_grade_entry_students'
        get 'student_interface'
      end

      resources :marks_graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_students_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

    end

    resources :notes do

      collection do
        post 'add_note'
        post 'noteable_object_selector'
        get 'new_update_groupings'
        post 'new_update_groupings'
      end

      member do
        get 'student_interface'
        get 'notes_dialog'
        post 'grades'
      end
    end

    resources :sections

    resources :annotations do
      collection do
        post 'add_existing_annotation'
        put 'update_annotation'
        post 'update_comment'
        delete 'destroy'
      end
    end

    resources :students do
      collection do
        post 'bulk_modify'
        post 'populate'
        get 'manage'
        get 'add_new_section'
        get 'download_student_list'
        post 'upload_student_list'
      end

      member do
        post 'delete_grace_period_deduction'
      end
    end

    resources :tas  do
      collection do
        post 'populate'
        post 'upload_ta_list'
        get 'download_ta_list'
      end
    end

    resources :main do
      collection do
        get 'logout'
        get 'about'
        post 'login_as'
        get 'role_switch'
        get 'redirect'
        get 'clear_role_switch_session'
        post 'reset_api_key'
      end
    end
  end

  match 'main', :controller => 'main', :action => 'index'
  match 'main/about', :controller => 'main', :action => 'about'
  match 'main/logout', :controller => 'main', :action => 'logout'

  # Return a 404 when no route is match
  match '*path', :controller => 'main', :action => 'page_not_found'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user, :foreign_key => :creator_id, :counter_cache => true
  belongs_to :noteable, :polymorphic => true, :counter_cache => true

  validates_presence_of :notes_message, :creator_id, :noteable
  validates_associated :user

  NOTEABLES = %w(Grouping Student Assignment)

  def user_can_modify?(current_user)
    current_user.admin? || user == current_user
  end

  def format_date
    I18n.l(created_at, :format => :long_date)
  end

  def self.noteables_exist?
    NOTEABLES.each do |classname|
      unless Kernel.const_get(classname).all.empty?
        return true
      end
    end
    return false
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authorize_for_ta_and_admin
  before_filter :ensure_can_modify, :only => [:edit, :update]

  # TODO this method needs explaining ! What is return_id ?
  def notes_dialog
    @return_id = params[:id]
    @cls = params[:noteable_type]
    @noteable = Kernel.const_get(@cls).find_by_id(params[:noteable_id])
    @cont = params[:controller_to]
    @action = params[:action_to]
    @highlight_field = params[:highlight_field]
    @number_of_notes_field = params[:number_of_notes_field]

    @notes = Note.all(:conditions => {:noteable_id => @noteable.id,
                                      :noteable_type => @noteable.class.name})
    render :partial => 'notes/modal_dialogs/notes_dialog_script',
      :formats => [:js], :handlers => [:erb]
  end

  def add_note
    return unless request.post?
    @note = Note.new
    @note.creator_id = @current_user.id
    @note.notes_message = params[:new_notes]
    @note.noteable_id = params[:noteable_id]
    @note.noteable_type = params[:noteable_type]
    unless @note.save
      render 'notes/modal_dialogs/notes_dialog_error',
        :formats => [:js], :handlers => [:erb]
    else
      @note.reload
      @number_of_notes_field = params[:number_of_notes_field]
      @highlight_field = params[:highlight_field]
      @number_of_notes = @note.noteable.notes.size
      render 'notes/modal_dialogs/notes_dialog_success',
        :formats => [:js], :handlers => [:erb]
    end
  end

  def index
    @notes = Note.all(:order => "created_at DESC", :include => [:user, :noteable])
    @current_user = current_user
    # Notes are attached to noteables, if there are no noteables, we can't make notes.
    @noteables_available = Note.noteables_exist?
		render 'index', :formats => [:html]
  end

  # gets the objects for groupings on first load.
  def new
    new_retrieve
    @note = Note.new
		render 'new', :formats => [:html], :handlers => [:erb]
  end

  def create
    @note = Note.new(params[:note])
    @note.noteable_type = params[:noteable_type]
    @note.creator_id = @current_user.id

    if @note.save
      flash[:success] = I18n.t('notes.create.success')
      redirect_to :action => 'index'
    else
      new_retrieve
      render 'new', :formats => [:html], :handlers => [:erb]
    end
  end

  # Used to update the values in the groupings dropdown in the new note form
  def new_update_groupings
    retrieve_groupings(Assignment.find(params[:assignment_id]))
    render 'new_update_groupings', :formats => [:js], :handlers => [:erb]
  end

  # used for RJS call
  def noteable_object_selector
    case params[:noteable_type]
      when 'Student'
        @students = Student.all(:order => 'user_name')
      when 'Assignment'
        @assignments = Assignment.all
      when 'Grouping'
        new_retrieve
      else
        # default to groupings if all else fails.
        params[:noteable_type] = 'Grouping'
        flash[:error] = I18n.t('notes.new.invalid_selector')
        new_retrieve
    end
		render 'noteable_object_selector', :formats => [:js], :handlers => [:erb]
  end

  def edit
		render 'edit', :formats => [:html], :handlers => [:erb]
  end

  def update
    if @note.update_attributes(params[:note])
      flash[:success] = I18n.t('notes.update.success')
      redirect_to :action => 'index'
    else
      render 'edit', :formats => [:html], :handlers => [:erb]
    end
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.user_can_modify?(current_user)
      @note.destroy
      flash[:success] = I18n.t('notes.delete.success')
    else
      flash[:error] = I18n.t('notes.delete.error_permissions')
    end
	  render 'destroy', :formats => [:js], :handlers => [:erb]
  end

  private
    def retrieve_groupings(assignment)
      if assignment.nil?
        @groupings = Array.new
        return
      end
      @groupings = Grouping.find_all_by_assignment_id(assignment.id,
        :include => [:group, {:student_memberships => :user}])
    end

    def new_retrieve
      @assignments = Assignment.all
      retrieve_groupings(@assignments.first)
    end

    # Renders a 404 error if the current user can't modify the given note.
    def ensure_can_modify
      @note = Note.find(params[:id])

      unless @note.user_can_modify?(current_user)
        render 'shared/http_status', :formats => [:html], :status => 404,
          :layout => false, :locals => {
            :code => '404', :message => HttpStatusHelper::ERROR_CODE['message']['404']
          }
      end
    end

end

app/views/notes/_assignment.html.erb
<%= fields_for :note do |f| %>
  <p>
    <%= f.label :noteable_id, I18n.t("notes.noteables.Assignment")%>
    <%= f.select :noteable_id, @assignments.map {|item| [item.short_identifier,item.id]}%>
  </p>
<% end %>

app/views/notes/_grouping.html.erb
<%= fields_for :note do |f| %>
  <p>
    <%= label_tag "assignment_id", I18n.t("notes.noteables.Assignment") %>
    <%= select_tag "assignment_id",
                   options_from_collection_for_select(
   @assignments,
   :id,
   :short_identifier),
   :onchange =>  "jQuery('#loading_groupings').show();
                  jQuery.ajax({
                    url: '" + new_update_groupings_notes_path() + "',
                    type: 'POST',
                    data: jQuery(this).serialize() + '&authenticity_token='+ AUTH_TOKEN,
                    async: true
                  }).done(function() {
                    jQuery('#loading_groupings').hide();
                  });"
    %>
  </p>

  <p>
    <%= f.label :noteable_id, I18n.t("notes.noteables.Grouping") %>
    <%= f.select :noteable_id,
     @groupings.collect {|p| [p.group_name_with_student_user_names,p.id]} %>
    <span id="loading_groupings" style="display:none">
    <%= image_tag('spinner.gif') %> <%= I18n.t('notes.new.loading_groupings') %>
    </span>
  </p>
<% end %>

app/views/notes/_student.html.erb
<%= fields_for :note do |f| %>
  <p>
  	<%= f.label :noteable_id, I18n.t("notes.noteables.Student") %>
	<%= f.select :noteable_id, @students.collect {|p| [p.user_name,p.id]} %>
  </p>
<% end %>

app/views/notes/destroy.js.erb
document.location.reload();

app/views/notes/edit.html.erb
<%= render :partial => "shared/navigation_warning",
  :formats => [:js], :handlers => [:erb] %>

<div id="title_bar"><h1><%=I18n.t('notes.edit.title')%></h1></div>

<div class="wrapLeft">
  <%= form_for @note, :as => :note, :url => {:action => 'update', :id => @note.id} do |f| %>
    <%= render :partial => "shared/error_explanation", :locals => { :model => @note } %>

    <p>
      <b><%=I18n.t('notes.author')%>:</b> <%= @note.user.user_name %>
    </p>

    <p>
      <b><%= I18n.t("notes.noteables.#{@note.noteable_type}") %>:</b> <%= @note.noteable.display_for_note %>
    </p>

    <p>
      <b><%=I18n.t('notes.creation_time')%>:</b> <%= @note.format_date %>
    </p>

    <p>
      <b><%= I18n.t('notes.note') %>:</b>
    </p>

    <%= raw(f.text_area :notes_message, :rows => 8, :cols => 50,
                        :onchange => "set_onbeforeunload(true);") %>

    <p>
      <%= f.submit I18n.t('save'), :disable_with => I18n.t('working'), :onclick => "set_onbeforeunload(false);" %>
    </p>
  <% end %>
</div>

app/views/notes/index.html.erb
<div id="title_bar"><h1><%=I18n.t('notes.title')  %></h1></div>

<div class="wrapLeft">

  <%= render 'shared/flash_message' %>

  <%
  #if there are no noteables,we can't add notes, so do not show Add New link.
  %>
  <% if @noteables_available %>
  <%= link_to I18n.t('notes.add_new'), { :action => 'new' }, :class => 'button' %>
  <% else %>
  <p><%= I18n.t('notes.new.no_noteables') %></p>
  <% end %>

<table id="notes">
<% for note in @notes %>
	<tr>
		<td class="note">
			<%= raw(I18n.t("notes.note_on",
				   :user_name => note.user.user_name,
				   :display_for => note.noteable.display_for_note )) %></b><br />
			<small><%=note.format_date%></small>
		</td>
		<td class="note"><%=note.notes_message%></td>
		<td class="note">
			<% if note.user_can_modify?(@current_user) -%>
				<%= button_to I18n.t('edit'),
	              edit_note_path(note.id),
	              :method => 'get',
	              :html => {:class => 'edit'},
	              :class => 'thin-button' %>
				<%= button_to I18n.t('delete'),
		          { :action => 'destroy', :id => note.id },
		          :html =>
		          { :class => 'delete',
		            :title => I18n.t('notes.delete.link_title') },
		          :confirm => I18n.t('notes.delete.link_confirm'),
		          :method => 'delete',
		          :remote => true,
		          :class => 'thin-button' %>
			<% else -%>
				&nbsp;
			<% end -%>
		</td>
	</tr>
<% end %>
</table>

</div>

app/views/notes/new.html.erb
<%= javascript_include_tag "notes" %>
<%= render :partial => "shared/navigation_warning",
  :formats => [:js], :handlers => [:erb] %>

<div id="title_bar"><h1><%= I18n.t('notes.new.title') %></h1></div>

<div class="wrapLeft">
  <%= form_for @note, :as => :note, :url => notes_path() do |f| %>
    <%= render :partial => "shared/error_explanation", :locals => { :model => @note } %>
    <fieldset>
      <p>
        <%= label_tag "noteable_type", I18n.t('notes.noteable') %>
        <%= select_tag "noteable_type",
           options_for_select(
              Note::NOTEABLES.map {|item| [I18n.t('notes.noteables.' + item),
                 item]}) %>
        <span id="loading_selector" style="display:none">
          <%= image_tag('spinner.gif') %> <%= I18n.t('notes.new.loading_selector') %>
        </span>
      </p>

      <div id="noteable_selector">
        <%= render  :partial => 'grouping' %>
      </div>

      <p>
        <%= raw(f.label :notes_message, I18n.t("notes.note")) %>
        <%= raw(f.text_area :notes_message, :rows => 10,
                            :onchange => "set_onbeforeunload(true);") %>
      </p>
    </fieldset>

    <%= f.submit I18n.t('save'), :onclick => "set_onbeforeunload(false);",
    							:disable_with => I18n.t('working') %>
    <%= link_to I18n.t('cancel'), notes_path(), :class => "button" %>
  <% end %>
</div>

app/views/notes/new_update_groupings.js.erb
jQuery('#note_noteable_id').html('<%= escape_javascript(options_from_collection_for_select(@groupings, :id, :group_name_with_student_user_names)).html_safe %>');

app/views/notes/noteable_object_selector.js.erb
jQuery('#noteable_selector').html('<%= escape_javascript(
             render :partial => params[:noteable_type].downcase).html_safe %>');