config/routes.rb
Markus::Application.routes.draw do
  # Install the default routes as the lowest priority.
  root :controller => "main", :action => "login"

  # optional path scope (denoted by the parentheses)
  scope "(:locale)", :locale => /en|fr|pt/  do
    # API routes
    namespace :api do
      resources :users, :except => [:new, :edit]
      resources :assignments, :except => [:new, :edit] do
        resources :groups, :except => [:new, :edit] do
          resources :submission_downloads, :except => [:new, :edit]
          resources :test_results, :except => [:new, :edit]
        end
      end
      resources :main_api
    end

    resources :admins do
      collection do
        post 'populate'
      end
    end

    resources :assignments do

      collection do
        get 'download_csv_grades_report'
        post 'update_group_properties_on_persist'
        get 'delete_rejected'
        post 'update_collected_submissions'
        get 'download_assignment_list'
        post 'upload_assignment_list'
      end

      member do
        get 'refresh_graph'
        get 'student_interface'
        get 'update_group_properties_on_persist'
        post 'invite_member'
        get 'creategroup'
        get 'join_group'
        get 'deletegroup'
        get 'decline_invitation'
        post 'disinvite_member'
        get 'render_test_result'
      end

      resources :rubrics do
        member do
          delete 'destroy'
          get 'move_criterion'
        end

        collection do
          post 'update_positions'
          post 'csv_upload'
          post 'yml_upload'
          get 'download_csv'
          get 'download_yml'
        end
      end

      resources :flexible_criteria do
        member do
          delete 'destroy'
          get 'move_criterion'
        end

        collection do
          post 'upload'
          post 'update_positions'
          get 'download'
        end
      end

      resources :automated_tests do
        collection do
          get 'manage'
          post 'update' # because of collection
          post 'update_positions'
          get 'update_positions'
          post 'upload'
          get 'download'
          get 'move_criterion'
        end
      end

      resources :groups do

        member do
          post 'rename_group'
          get 'rename_group_dialog'
        end

        collection do
          post 'populate'
          post 'populate_students'
          get 'add_group'
          get 'use_another_assignment_groups'
          get 'manage'
          post 'csv_upload'
          get 'add_csv_group'
          get 'download_grouplist'
          get 'create_groups_when_students_work_alone'
          get 'valid_grouping'
          get 'invalid_grouping'
          get 'global_actions'
          get 'rename_group'
          delete 'remove_group'
          post 'add_group'
          post 'global_actions'
        end
      end

      resources :submissions do
        collection do
          get 'file_manager'
          get 'browse'
          post 'populate_file_manager'
          get 'collect_all_submissions'
          get 'download_simple_csv_report'
          get 'download_detailed_csv_report'
          get 'download_svn_export_list'
          get 'download_svn_export_commands'
          get 'download_svn_repo_list'
          get 'collect_ta_submissions'
          post 'update_submissions'
          post 'populate_repo_browser'
          post 'update_converted_pdfs'
          get 'updated_files'
          get 'replace_files'
          get 'delete_files'
          post 'update_files'
          post 'server_time'
          get 'download'
          get 'download_groupings_files'
        end

        member do
          get 'collect_and_begin_grading'
          post 'manually_collect_and_begin_grading'
          get 'repo_browser'
          post 'repo_browser'
          get 'downloads'
        end

        resources :results do
          collection do
            post 'update_mark'
            get 'expand_criteria'
            get 'collapse_criteria'
            get 'expand_unmarked_criteria'
            get 'edit'
            get 'download'
          end

          member do
            get 'add_extra_marks'
            get 'add_extra_mark'
            get 'download'
            post 'download'
            get 'download_zip'
            get 'cancel_remark_request'
            get 'codeviewer'
            post 'codeviewer'
            get 'expand_criteria'
            get 'collapse_criteria'
            post 'add_extra_mark'
            post 'delete_grace_period_deduction'
            get 'next_grouping'
            post 'remove_extra_mark'
            get 'expand_unmarked_criteria'
            post 'set_released_to_students'
            put 'update_overall_comment'
            post 'update_overall_remark_comment'
            post 'update_marking_state'
            get 'update_remark_request'
            get 'update_positions'
            post 'update_mark'
            get 'view_marks'
          end
        end
      end

      resources :graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_groupings_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

      resources :annotation_categories do
        member do
          get 'get_annotations'
          delete 'delete_annotation_category'
          delete 'delete_annotation_text'
          get 'add_annotation_text'
          post 'add_annotation_text'
          put 'update_annotation'
        end

        collection do
          get 'add_annotation_category'
          post 'csv_upload'
          get 'delete_annotation_category'
          get 'download'
          post 'yml_upload'
          post 'add_annotation_category'
          post 'update_annotation_category'
          get 'add_annotation_text'
          post 'delete_annotation_text'
          post 'update_annotation'
        end
      end
    end

    resources :grade_entry_forms do
      collection do
        get 'student_interface'
      end

      member do
        get 'grades'
        get 'g_table_paginate'
        post 'g_table_paginate'
        get 'csv_download'
        post 'csv_upload'
        post 'update_grade'
        post 'update_grade_entry_students'
        get 'student_interface'
      end

      resources :marks_graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_students_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

    end

    resources :notes do

      collection do
        post 'add_note'
        post 'noteable_object_selector'
        get 'new_update_groupings'
        post 'new_update_groupings'
      end

      member do
        get 'student_interface'
        get 'notes_dialog'
        post 'grades'
      end
    end

    resources :sections

    resources :annotations do
      collection do
        post 'add_existing_annotation'
        put 'update_annotation'
        post 'update_comment'
        delete 'destroy'
      end
    end

    resources :students do
      collection do
        post 'bulk_modify'
        post 'populate'
        get 'manage'
        get 'add_new_section'
        get 'download_student_list'
        post 'upload_student_list'
      end

      member do
        post 'delete_grace_period_deduction'
      end
    end

    resources :tas  do
      collection do
        post 'populate'
        post 'upload_ta_list'
        get 'download_ta_list'
      end
    end

    resources :main do
      collection do
        get 'logout'
        get 'about'
        post 'login_as'
        get 'role_switch'
        get 'redirect'
        get 'clear_role_switch_session'
        post 'reset_api_key'
      end
    end
  end

  match 'main', :controller => 'main', :action => 'index'
  match 'main/about', :controller => 'main', :action => 'about'
  match 'main/logout', :controller => 'main', :action => 'logout'

  # Return a 404 when no route is match
  match '*path', :controller => 'main', :action => 'page_not_found'
end

app/helpers/graders_helper.rb
module GradersHelper

  # Given a list of criteria and an assignment, constructs an array of
  # table rows to be insterted into the criteria FilterTable in the graders view.
  # Called whenever it is necessary to update the criteria table with multiple
  # changes.
  def construct_criterion_table_rows(criteria, assignment)
    result = {}
    criteria.each do |criterion|
      result[criterion.id] = construct_criterion_table_row(criterion, assignment)
    end
    result
  end

  # Given a list of graders and an assignment, constructs an array of
  # table rows to be insterted into the graders FilterTable in the graders view.
  # Called whenever it is necessary to update the graders table with multiple
  # changes.
  def construct_grader_table_rows(graders, assignment)
    result = {}
    graders.each do |grader|
      result[grader.id] = construct_grader_table_row(grader, assignment)
    end
    result
  end

  # Given a list of groupings and an assignment, constructs an array of
  # table rows to be insterted into the groupings FilterTable in the graders view.
  # Called whenever it is necessary to update the groupings table with multiple
  # changes.
  def construct_table_rows(groupings, assignment)
    result = {}
    total_criteria_count = assignment.criteria_count
    groupings.each do |grouping|
      result[grouping.id] = construct_table_row(grouping, assignment, total_criteria_count)
    end
    result
  end

  def construct_table_row(grouping, assignment, total_criteria_count)
      table_row = {}

      table_row[:id] = grouping.id
      table_row[:filter_table_row_contents] =
        render_to_string :partial => 'graders/table_row/filter_table_row',
        :formats => [:html], :handlers => [:erb],
        :locals => { :grouping => grouping,
                     :assignment => assignment,
                     :total_criteria_count => total_criteria_count }

      #These are used for sorting
      table_row[:name] = grouping.group.group_name
      table_row[:members] = grouping.tas.collect{ |grader| grader.user_name}.join(',')
      table_row[:coverage] = grouping.criteria_coverage_count

      #These 2 are used for searching
      table_row[:graders] = table_row[:members]
      table_row[:grader_names] = grouping.get_ta_names.join(',')

      #This one is used for selection
      table_row[:section] = grouping.section

      table_row
  end

  # Given a grader and an assignment, constructs a table row to be insterted
  # into the grader FilterTable in the graders view.  Called whenever it
  # is necessary to update the graders table.
  def construct_grader_table_row(grader, assignment)
    table_row = {}

    table_row[:id] = grader.id
    table_row[:filter_table_row_contents] =
      render_to_string :partial => 'graders/table_row/filter_table_grader_row',
      :locals => {:grader => grader}

    #These used only for searching
    table_row[:first_name] = grader.first_name
    table_row[:last_name] = grader.last_name

    #These needed for sorting
    table_row[:user_name] = grader.user_name
    table_row[:full_name] = "#{grader.first_name} #{grader.last_name}"
    table_row[:num_groups] = grader.get_membership_count_by_assignment(assignment)
    table_row[:num_criteria] = grader.get_criterion_associations_count_by_assignment(assignment)

    table_row
  end

  # Given a criterion and an assignment, constructs a table row to be insterted
  # into the criteria FilterTable in the graders view.  Called whenever it
  # is necessary to update the criteria table.
  def construct_criterion_table_row(criterion, assignment)
    table_row = {}

    table_row[:id] = criterion.id
    table_row[:filter_table_row_contents] =
      render_to_string :partial => 'graders/table_row/filter_table_criterion_row',
      :formats => [:html], :handlers => [:erb],
      :locals => {:criterion => criterion, :assignment => assignment}

    table_row[:criterion_name] = criterion.get_name
    table_row[:members] = criterion.get_ta_names.to_s
    table_row[:coverage] = criterion.assigned_groups_count

    table_row
  end
end

app/views/graders/_boot.js.erb
<script type="text/javascript">
//<![CDATA[

var groupings_table = null;

document.observe("dom:loaded", function() {
  // Hide AJAX errors DIV
  $('errors').hide();

  //force the middle column to be moved on the y-axis as the page is scrolled
	Event.observe(document, "scroll", function() {
		//110 is the displacement for "top" for .centreColumnGraders as can be seen in the main.css
		$("centreColumn").setStyle({top: (document.viewport.getScrollOffsets().top + 110) +'px' });
	});

  groupings_table = new FilterTable({
    table_id: $('groups'),
    headers: {
      name: {display: "<%= I18n.t('name') %>", sortable: true},
      section: {display: "<%= I18n.t('graders.section') %>", sortable: true},
      members: {display: "<%= I18n.t('graders.graders') %>", sortable: true, sort_with: 'nohtml'},
      coverage: {display: "<%= I18n.t('graders.coverage') if @assignment.assign_graders_to_criteria %>", sortable: true}
    },
    can_select: true,
    can_select_all: true,
    select_all_header: "<%= I18n.t('all') %>",
    can_sort: true,
    row_prefix: "groupings_row_",
    select_name: "groupings[]",
    select_id_prefix: "grouping_select_",
    select_all_top_id: "grouping_select_all_top",
    select_all_bottom_id: "grouping_select_all_bottom",
    selectable_class: "FilterTable_groupings_selectable",
    select_onclick: "check_all(this.id.split('_')[2],this.checked)",
    footer: true,
    default_sort: 'name',
    header_id_prefix: "FilterTable_manage_graders_header_",
    filters: {
      validated: function(row) {
        return row.filter_valid;
      },
      unvalidated: function(row) {
        return !row.filter_valid;
      },
      search: function(row) {
        return (row.name.toLowerCase().indexOf($('search_groupings').value.toLowerCase()) != -1
        || row.graders.toLowerCase().indexOf($('search_groupings').value.toLowerCase()) != -1
        || row.grader_names.toLowerCase().indexOf($('search_groupings').value.toLowerCase()) != -1);
      },
      selection: function(row) {
        return (row.section.toLowerCase() ==
                  $('selection_groupings_sections').value.toLowerCase() ||
                $('selection_groupings_sections').value.toLowerCase() == '');
      }
    },
    after_filter_only_by: function(current_filters, new_filter) {
      $('filter_link_none').removeClassName('filter_selected');
      current_filters.each(function(filter_key) {
        if(filter_key != 'search') {
          $('filter_link_' + filter_key).removeClassName('filter_selected');
        }
      });
      $('filter_link_' + new_filter).addClassName('filter_selected');
    },
    after_clear_filters: function(current_filters) {
      current_filters.each(function(filter_key) {
        if(filter_key != 'search') {
          $('filter_link_' + filter_key).removeClassName('filter_selected');
        }
      });
      $('filter_link_none').addClassName('filter_selected');
    },
    sorts: {
      nohtml: function(a, b) {
        return a[FILTERTABLE_SORT].stripTags().toLowerCase() > b[FILTERTABLE_SORT].stripTags().toLowerCase() ? 1 : -1;
        }
    },
    total_count_id: 'all_groupings_count',
    filter_count_ids: {
      validated: 'valid_groupings_count',
      unvalidated: 'invalid_groupings_count'
    }
  });


  graders_table = new FilterTable({
    table_id: $('graders'),
    headers: {
      user_name: {display: "<%= I18n.t('user.user_name') %>", sortable: true},
      full_name: {display: "<%= I18n.t('user.full_name') %>", sortable: true},
      num_groups: {display: "<%= I18n.t('groups.groups') %>", sortable: true},
      num_criteria: {display: "<%= I18n.t('criteria') %>", sortable: true}
    },
    can_select: true,
    can_select_all: true,
    select_all_header: "<%= I18n.t('all') %>",
    can_sort: true,
    row_prefix: "graders_row_",
    select_name: "graders[]",
    select_id_prefix: "grader_select_",
    select_all_top_id: "grader_select_all_top",
    select_all_bottom_id: "grader_select_all_bottom",
    selectable_class: "FilterTable_graders_selectable",
    footer: true,
    default_sort: 'user_name',
    default_filters: [],
    filters: {
      assigned: function(row) {
        return row.filter_grader_assigned;
      },
      unassigned: function(row) {
        return !row.filter_grader_assigned;
      },
      search: function(row) {
        return (row.user_name.toLowerCase().indexOf($('search_graders').value.toLowerCase()) != -1
        || row.first_name.toLowerCase().indexOf($('search_graders').value.toLowerCase()) != -1
        || row.last_name.toLowerCase().indexOf($('search_graders').value.toLowerCase()) != -1);
      }
    },
    after_filter_only_by: function(current_filters, new_filter) {
      $('filter_link_graders_none').removeClassName('filter_selected');
      current_filters.each(function(filter_key) {
        if(filter_key != 'search') {
          $('filter_link_graders_' + filter_key).removeClassName('filter_selected');
        }
      });
      $('filter_link_graders_' + new_filter).addClassName('filter_selected');
    },
    after_clear_filters: function(current_filters) {
      current_filters.each(function(filter_key) {
        if(filter_key != 'search') {
          $('filter_link_graders_' + filter_key).removeClassName('filter_selected');
        }
      });
      $('filter_link_graders_none').  addClassName('filter_selected');
    },
    total_count_id: 'all_graders_count',
    filter_count_ids: {
      assigned: 'assigned_graders_count',
      unassigned: 'unassigned_graders_count'
    }
  });


  criteria_table = new FilterTable({
    table_id: $('criteria'),
    headers: {
      criterion_name: {display: "<%= I18n.t('criterion_name') %>", sortable: true},
      members: {display: "<%= I18n.t('graders.graders') %>", sortable: true, sort_with: 'nohtml'},
      coverage: {display: "<%= I18n.t('graders.coverage') %>", sortable: true}
    },
    can_select: true,
    can_select_all: true,
    select_all_header: "<%= I18n.t('all') %>",
    can_sort: true,
    row_prefix: "criteria_row_",
    select_name: "criteria[]",
    select_id_prefix: "criterion_select_",
    select_all_top_id: "criterion_select_all_top",
    select_all_bottom_id: "criterion_select_all_bottom",
    selectable_class: "FilterTable_criteria_selectable",
    select_onclick: "check_all(this.id.split('_')[2],this.checked)",
    footer: true,
    default_sort: 'criterion_name',
    default_filters: [],
    filters: {
      search: function(row) {
        return (row.criterion_name.toLowerCase().indexOf($('search_criteria').value.toLowerCase()) != -1
             || row.members.toLowerCase().indexOf($('search_criteria').value.toLowerCase()) != -1);
      }
    },
    after_filter_only_by: function(current_filters, new_filter) {
      $('filter_link_criteria_none').removeClassName('filter_selected');
      current_filters.each(function(filter_key) {
        if(filter_key != 'search') {
          $('filter_link_criteria_' + filter_key).removeClassName('filter_selected');
        }
      });
      $('filter_link_criteria_' + new_filter).addClassName('filter_selected');
    },
    after_clear_filters: function(current_filters) {
      current_filters.each(function(filter_key) {
        if(filter_key != 'search') {
          $('filter_link_criteria_' + filter_key).removeClassName('filter_selected');
        }
      });
      $('filter_link_criteria_none').  addClassName('filter_selected');
    },
    total_count_id: 'all_criteria_count',
    sorts: {
      nohtml: function(a, b) {
        return a[FILTERTABLE_SORT].stripTags().toLowerCase() > b[FILTERTABLE_SORT].stripTags().toLowerCase() ? 1 : -1;
        }
    }
  });

  new Ajax.Request('<%= populate_graders_assignment_graders_path(@assignment) %>', {
    asynchronous: true,
    evalScripts: true,
    onComplete: function(request){$('loading_graders_list').hide()},
    parameters: {
      'authenticity_token': AUTH_TOKEN
    }
  });

  new Ajax.Request('<%= populate_assignment_graders_path(@assignment) %>', {
    asynchronous: true,
    evalScripts: true,
    onComplete: function(request){$('loading_list').hide()},
    parameters: {
      'authenticity_token': AUTH_TOKEN
    }
  });

  <% if !@assignment.assign_graders_to_criteria %>
    $('criteria').hide();
    $('search_criteria').hide();
    $('search_criteria_label').hide();
  <% else %>
    new Ajax.Request('<%= populate_criteria_assignment_graders_path(@assignment) %>', {
      asynchronous: true,
      evalScripts: true,
      onComplete: function(request){$('loading_list').hide()},
      parameters: {
        'authenticity_token': AUTH_TOKEN
      }
    });
  <% end %>
});

//]]>
</script>

app/views/graders/index.html.erb
<%= javascript_include_tag 'manage_graders.js',
                           'FilterTable/FilterTable.js',
                           'Graders/tabs_boot.js',
                           'Graders/index' %>

<%= render :partial => "boot", :formats => [:js], :handlers => [:erb] %>

<div id="title_bar">
  <h1><%= I18n.t("graders.manage_graders") %></h1>
  <div class="colRightGroups">
      <div class="headingButtons">
      <%= button_to_function I18n.t('download'), 'modal_download.open();' %>
      <span class="menu_bar">|</span>
      <%= button_to_function I18n.t('upload'), 'modal_upload.open();' %>
    </div> <!-- rightjustify-->
  </div> <!-- colrightgroups-->

  </div> <!-- title_bar-->


<div class="wrapLeft">
</div>

<div class="clear"></div>

<div id="notice">
  <div class="success" id="add_success" style="display: none; "></div>
  <% # This is for error display injected by JavaScript %>

  <div class="error" id="errors" style="display: none; ">
    <h3><%= t("graders.problem") %></h3>
    <div id="errors_title">
    </div>
    <div id="errors_contents">
    </div>
  </div>

  <div class="warning" id="global_action_warning" style="display: none; ">
    <h3><%= t("groups.warning") %></h3>
    <div id="global_action_warning_msg"></div>
  </div>

  <% # all other flash messages %>
  <%= render 'shared/flash_message' %>
</div><!-- Notice -->

<%= form_tag global_actions_assignment_graders_path(@assignment),
             :id => "global_action_form",
             :remote => true do %>

<script type='text/javascript'>
$("global_action_form").observe('ajax:after', function(evt, status, data, xhr) {
  thinking();
});

$("global_action_form").observe('ajax:success', function(evt, status, data, xhr) {
  done_thinking();
});
</script>

<%= hidden_field_tag 'submit_type', 'global_action', :id => 'submit_type' %>
<%= hidden_field_tag 'current_table', 'groups_table', :id => 'current_table' %>
<%= hidden_field_tag 'global_actions'%>

<div class="clear"></div>
<div class="colsLeftHeavy">
  <div class="colRightGraders">
    <div class="wrapRightGroups">
      <div class="pane">
        <span id="loading_list">
          <%= image_tag("spinner.gif") %><%= t("groups.loading_list") %></span>
        <ul id="groups_tabs"class="subsection_tabs">
          <li class="tab">
            <a href="#groups_table" id="filter_link_none" class="filter_selected">
              <%= I18n.t("groups.groups") %></a></li>
        <li class="tab">
            <a href="#criteria_table" id="filter_link_criteria_none" class="filter_selected">
              <%= I18n.t("criteria") %></a></li>
        </ul>

        <div id="criteria_table">
          <div id="criteria_container" class="tabbedArea">
            <%= label_tag 'search_criteria', I18n.t('search'),
              :class => 'bold_inline_label',
              :id => 'search_criteria_label' %>
            <%= text_field_tag 'search_criteria', nil,
              :onkeyup => "criteria_table.add_filter('search'); criteria_table.render();",
              :onkeypress => "stop_submit(event);"%>
            <%= check_box_tag 'assign_criteria', true,
              @assignment.assign_graders_to_criteria,
              :class => 'inline_checkbox', 'data-action' => url_for(:action => :set_assign_criteria, :id => @assignment.id)%>
            <%= label_tag 'assign_criteria', I18n.t('graders.assign_to_criteria'),
              :class => 'bold_inline_label'%>

            <table class="criteria" id="criteria">
            </table>

          </div><!-- group container -->
        </div>

        <div id="groups_table">
          <div class="clear"></div>

          <div id="groups_container" class="tabbedArea">
            <%= label_tag 'search_groupings', I18n.t('search'),
              :class => 'bold_inline_label',
              :id => 'search_groupings_label' %>
            <%= text_field_tag 'search_groupings', nil,
              :onkeyup => "groupings_table.add_filter('search'); groupings_table.render();",
              :onkeypress => "stop_submit(event);" %>

            <label class="bold_inline_label"><%= t('browse_submissions.sections') %></label>
            <%= select('selection_groupings', 'sections',
                       Section.all.collect { |s| [s.name] },
                       { :include_blank => ' - ' },
                       { :onchange => 'groupings_table.add_filter("selection");
                       return groupings_table.render();',
                         :onfocus => 'stop_submit(event);' }) %>

            <table class="groups" id="groups">
            </table>
          </div><!-- group container -->
        </div>
      </div>
    </div>
  </div> <!-- colRightGroups -->

  <div class="colLeftGraders">
    <% # order of processing students is important. we go through each member
       # one by one and delete them above from the list of students
       # if they are already in a group
       # See manage/_group.html.erb
    %>
    <div class="wrapLeftGroups">
      <div class="pane">
        <span id="loading_graders_list">
          <%= image_tag("spinner.gif") %><%= t("groups.loading_list") %></span>
        <ul id="graders_tabs" class="subsection_tabs">
          <li class="tab">
            <a href="#graders_none" id="filter_link_graders_none"  class="filter_selected">
              <%= I18n.t("graders.graders") %></a></li>
        </ul>

        <div id="graders_none"></div>
        <div id="unassigned"></div>
        <div id="assigned"></div>

        <div class="tabbedArea">
          <div class="searchBox">
            <%= label_tag 'search_graders', "Search:",
              :class => 'bold_inline_label'%>
            <%= text_field_tag 'search_graders', nil,
               :onkeyup => "graders_table.add_filter('search'); graders_table.render();",
               :onkeypress => "stop_submit(event);" %>
          </div>
          <table class="graders" id="graders">
          </table>
        </div>

      </div>
    </div>
  </div> <!-- colLeftGroups -->

  <div id="centreColumn" class="centreColumnGraders">
      <%= image_submit_tag "random_arrow.png",
        :onclick => "$('global_actions').setValue('random_assign');",
        :alt => I18n.t('groups.randomly_assign_graders'),
        :title => I18n.t('groups.randomly_assign_graders'),
        :class =>'image_input' %>
      <br/><br/>
      <%= image_submit_tag "add_arrow.png",
        :onclick => "$('global_actions').setValue('assign');",
        :alt => I18n.t('add_graders'),
        :class =>'image_input',
        :title => I18n.t('add_graders') %>
      <br/><br/>
      <%= image_submit_tag "remove_arrow.png",
        :onclick => "$('global_actions').setValue('unassign');",
        :alt => I18n.t('remove_graders'),
        :title => I18n.t('remove_graders'),
        :class =>'image_input' %>
  </div>

</div> <!-- ColsLeftHeavy -->
<% end %> <!-- remote form tag -->

<!-- Modal Windows -->

<div id="download_dialog">
  <h2><%= t('groups.download.download_grader_maps') %></h2>
  <ul>
    <li><%= link_to t('groups.download.download_grader_groups_csv'),
		    download_grader_groupings_mapping_assignment_graders_path(@assignment),
		    :onclick => 'modal_download.close();' %></li>
    <li><%= link_to t('groups.download.download_grader_criteria_csv'),
		    download_grader_criteria_mapping_assignment_graders_path(@assignment),
		    :onclick => 'modal_download.close();' %></li>
  </ul>
  <%= button_to_function I18n.t('cancel'), 'modal_download.close();' %>
</div>

<div id="upload_dialog">
  <h2><%= I18n.t("groups.upload.upload_grader_map") %></h2>
  <%= raw(I18n.t("groups.upload.description_grader_map")) %>
  <%= form_tag({:controller=>"graders",
    :action => 'csv_upload_grader_groups_mapping',:id => @assignment.id},
    {:multipart => true}) do %>
    <br />
    <br />
    <%= I18n.t("encoding") %>
    <%= select_tag(:encoding, options_for_select(@encodings)) %>
    <br />
    <br />
    <p><%= file_field_tag :grader_mapping, :size => 2 %> <br />
      <%= submit_tag t(:upload), :disable_with => t(:uploading_please_wait) %>
      <%= button_to_function I18n.t('cancel'), 'modal_upload.close();' %>
    </p>
  <% end %>

  <% if @assignment.assign_graders_to_criteria %>
    <h2><%= I18n.t("groups.upload.upload_grader_criteria_map") %></h2>
    <%= raw(I18n.t("groups.upload.description_grader_criteria_map")) %>
    <%= form_tag({:controller=>"graders",
      :action => 'csv_upload_grader_criteria_mapping',:id => @assignment.id},
      {:multipart => true}) do %>
      <br />
      <br />
      <%= I18n.t("encoding") %>
      <%= select_tag(:encoding, options_for_select(@encodings)) %>
      <br />
      <br />
      <p><%= file_field_tag :grader_criteria_mapping, :size => 2 %> <br />
        <%= submit_tag t(:upload), :disable_with => t(:uploading_please_wait) %>
        <%= button_to_function I18n.t('cancel'), 'modal_upload.close();' %>
      </p>
    <% end %>
  <% end %>
</div>

<div id="groups_coverage_dialog">
</div>

<div id="grader_criteria_dialog">
</div>