config/routes.rb
Markus::Application.routes.draw do
  # Install the default routes as the lowest priority.
  root :controller => "main", :action => "login"

  # optional path scope (denoted by the parentheses)
  scope "(:locale)", :locale => /en|fr|pt/  do
    # API routes
    namespace :api do
      resources :users, :except => [:new, :edit]
      resources :assignments, :except => [:new, :edit] do
        resources :groups, :except => [:new, :edit] do
          resources :submission_downloads, :except => [:new, :edit]
          resources :test_results, :except => [:new, :edit]
        end
      end
      resources :main_api
    end

    resources :admins do
      collection do
        post 'populate'
      end
    end

    resources :assignments do

      collection do
        get 'download_csv_grades_report'
        post 'update_group_properties_on_persist'
        get 'delete_rejected'
        post 'update_collected_submissions'
        get 'download_assignment_list'
        post 'upload_assignment_list'
      end

      member do
        get 'refresh_graph'
        get 'student_interface'
        get 'update_group_properties_on_persist'
        post 'invite_member'
        get 'creategroup'
        get 'join_group'
        get 'deletegroup'
        get 'decline_invitation'
        post 'disinvite_member'
        get 'render_test_result'
      end

      resources :rubrics do
        member do
          delete 'destroy'
          get 'move_criterion'
        end

        collection do
          post 'update_positions'
          post 'csv_upload'
          post 'yml_upload'
          get 'download_csv'
          get 'download_yml'
        end
      end

      resources :flexible_criteria do
        member do
          delete 'destroy'
          get 'move_criterion'
        end

        collection do
          post 'upload'
          post 'update_positions'
          get 'download'
        end
      end

      resources :automated_tests do
        collection do
          get 'manage'
          post 'update' # because of collection
          post 'update_positions'
          get 'update_positions'
          post 'upload'
          get 'download'
          get 'move_criterion'
        end
      end

      resources :groups do

        member do
          post 'rename_group'
          get 'rename_group_dialog'
        end

        collection do
          post 'populate'
          post 'populate_students'
          get 'add_group'
          get 'use_another_assignment_groups'
          get 'manage'
          post 'csv_upload'
          get 'add_csv_group'
          get 'download_grouplist'
          get 'create_groups_when_students_work_alone'
          get 'valid_grouping'
          get 'invalid_grouping'
          get 'global_actions'
          get 'rename_group'
          delete 'remove_group'
          post 'add_group'
          post 'global_actions'
        end
      end

      resources :submissions do
        collection do
          get 'file_manager'
          get 'browse'
          post 'populate_file_manager'
          get 'collect_all_submissions'
          get 'download_simple_csv_report'
          get 'download_detailed_csv_report'
          get 'download_svn_export_list'
          get 'download_svn_export_commands'
          get 'download_svn_repo_list'
          get 'collect_ta_submissions'
          post 'update_submissions'
          post 'populate_repo_browser'
          post 'update_converted_pdfs'
          get 'updated_files'
          get 'replace_files'
          get 'delete_files'
          post 'update_files'
          post 'server_time'
          get 'download'
          get 'download_groupings_files'
        end

        member do
          get 'collect_and_begin_grading'
          post 'manually_collect_and_begin_grading'
          get 'repo_browser'
          post 'repo_browser'
          get 'downloads'
        end

        resources :results do
          collection do
            post 'update_mark'
            get 'expand_criteria'
            get 'collapse_criteria'
            get 'expand_unmarked_criteria'
            get 'edit'
            get 'download'
          end

          member do
            get 'add_extra_marks'
            get 'add_extra_mark'
            get 'download'
            post 'download'
            get 'download_zip'
            get 'cancel_remark_request'
            get 'codeviewer'
            post 'codeviewer'
            get 'expand_criteria'
            get 'collapse_criteria'
            post 'add_extra_mark'
            post 'delete_grace_period_deduction'
            get 'next_grouping'
            post 'remove_extra_mark'
            get 'expand_unmarked_criteria'
            post 'set_released_to_students'
            put 'update_overall_comment'
            post 'update_overall_remark_comment'
            post 'update_marking_state'
            get 'update_remark_request'
            get 'update_positions'
            post 'update_mark'
            get 'view_marks'
          end
        end
      end

      resources :graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_groupings_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

      resources :annotation_categories do
        member do
          get 'get_annotations'
          delete 'delete_annotation_category'
          delete 'delete_annotation_text'
          get 'add_annotation_text'
          post 'add_annotation_text'
          put 'update_annotation'
        end

        collection do
          get 'add_annotation_category'
          post 'csv_upload'
          get 'delete_annotation_category'
          get 'download'
          post 'yml_upload'
          post 'add_annotation_category'
          post 'update_annotation_category'
          get 'add_annotation_text'
          post 'delete_annotation_text'
          post 'update_annotation'
        end
      end
    end

    resources :grade_entry_forms do
      collection do
        get 'student_interface'
      end

      member do
        get 'grades'
        get 'g_table_paginate'
        post 'g_table_paginate'
        get 'csv_download'
        post 'csv_upload'
        post 'update_grade'
        post 'update_grade_entry_students'
        get 'student_interface'
      end

      resources :marks_graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_students_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

    end

    resources :notes do

      collection do
        post 'add_note'
        post 'noteable_object_selector'
        get 'new_update_groupings'
        post 'new_update_groupings'
      end

      member do
        get 'student_interface'
        get 'notes_dialog'
        post 'grades'
      end
    end

    resources :sections

    resources :annotations do
      collection do
        post 'add_existing_annotation'
        put 'update_annotation'
        post 'update_comment'
        delete 'destroy'
      end
    end

    resources :students do
      collection do
        post 'bulk_modify'
        post 'populate'
        get 'manage'
        get 'add_new_section'
        get 'download_student_list'
        post 'upload_student_list'
      end

      member do
        post 'delete_grace_period_deduction'
      end
    end

    resources :tas  do
      collection do
        post 'populate'
        post 'upload_ta_list'
        get 'download_ta_list'
      end
    end

    resources :main do
      collection do
        get 'logout'
        get 'about'
        post 'login_as'
        get 'role_switch'
        get 'redirect'
        get 'clear_role_switch_session'
        post 'reset_api_key'
      end
    end
  end

  match 'main', :controller => 'main', :action => 'index'
  match 'main/about', :controller => 'main', :action => 'about'
  match 'main/logout', :controller => 'main', :action => 'logout'

  # Return a 404 when no route is match
  match '*path', :controller => 'main', :action => 'page_not_found'
end

app/controllers/api/groups_controller.rb
module Api

  # Allows for listing Markus groups for a particular assignment.
  # Uses Rails' RESTful routes (check 'rake routes' for the configured routes)
  class GroupsController < MainApiController
    # Define default fields to display for index and show methods
    @@default_fields = [:id, :group_name, :created_at, :updated_at, :first_name,
                        :last_name, :user_name, :membership_status,
                        :student_memberships]

    # Returns an assignment's groups along with their attributes
    # Requires: assignment_id
    # Optional: filter, fields
    def index
      assignment = Assignment.find_by_id(params[:assignment_id])
      if assignment.nil?
        # No assignment with that id
        render 'shared/http_status', :locals => {:code => '404', :message =>
          'No assignment exists with that id'}, :status => 404
        return
      end

      collection = Group.joins(:assignments).where(:assignments =>
        {:id => params[:assignment_id]})
      groups = get_collection(Group, collection)
      fields = fields_to_render(@@default_fields)

      students = include_students(fields)

      respond_to do |format|
        format.xml{render :xml => groups.to_xml(:only => fields, :root =>
          'groups', :skip_types => 'true', :include => students)}
        format.json{render :json => groups.to_json(:only => fields,
          :include => students)}
      end
    end

    # Returns a single group along with its attributes
    # Requires: assignment_id, id
    # Optional: fields
    def show
      # Error if no assignment exists with that id
      assignment = Assignment.find_by_id(params[:assignment_id])
      if assignment.nil?
        render 'shared/http_status', :locals => {:code => '404', :message =>
          'No assignment exists with that id'}, :status => 404
        return
      end

      # Error if no group exists with that id
      group = Group.find_by_id(params[:id])
      if group.nil?
        render 'shared/http_status', :locals => {:code => '404', :message =>
          'No group exists with that id'}, :status => 404
        return
      end

      if group.grouping_for_assignment(params[:assignment_id])
        # We found a grouping for that assignment
        fields = fields_to_render(@@default_fields)
        students = include_students(fields)

        respond_to do |format|
          format.xml{render :xml => group.to_xml(:only => fields, :root =>
            'group', :skip_types => 'true', :include => students)}
          format.json{render :json => group.to_json(:only => fields,
            :include => students)}
        end
      else
        # The group doesn't have a grouping associated with that assignment
        render 'shared/http_status', :locals => {:code => '422', :message =>
          'The group is not involved with that assignment'}, :status => 422
      end
    end

    # Include student_memberships and user info if required
    def include_students(fields)
      if fields.include?(:student_memberships)
        {:student_memberships => {:include => :user}}
      end
    end

  end # end GroupsController
end

app/helpers/groups_helper.rb
module GroupsHelper

  # Given a list of groupings and an assignment, constructs an array of table
  # rows to be insterted into the groupings FilterTable in the groups view.
  # Called whenever it is necessary to update the groupings table with multiple
  # changes.
  def construct_table_rows(groupings, assignment)
    result = {}
    groupings.each do |grouping|
      result[grouping.id] = construct_table_row(grouping, assignment)
    end
    result
  end

  # Given a list of students and an assignment, constructs an array of
  # table rows to be insterted into the students FilterTable in the groups view.
  # Called whenever it is necessary to update the students table with multiple
  # changes.
  def construct_student_table_rows(students, assignment)
    student_memberships = StudentMembership.all(:conditions => {:grouping_id => assignment.groupings, :user_id => students})
    students_in_assignment = student_memberships.collect do |membership|
      membership.user
    end
    result = {}
    students.each do |student|
      result[student.id] = construct_student_table_row(student, students_in_assignment)
    end
    result
  end

  # Given a grouping and an assignment, constructs a table row to be insterted
  # into the groupings FilterTable in the groups view.  Called whenever it
  # is necessary to update the groupings table.
  def construct_table_row(grouping, assignment)
      table_row = {}

      table_row[:id] = grouping.id
      table_row[:filter_table_row_contents] =
          render_to_string :partial => 'groups/table_row/filter_table_row',
                           :formats => [:html],
                           :handlers => [:erb],
                           :locals => {
                               :grouping => grouping,
                               :assignment => assignment }

      table_row[:name] = grouping.group.group_name

      table_row[:members] = grouping.students.collect{ |student| student.user_name}.join(',')

#      used for searching
      table_row[:student_names] = grouping.students.collect{ |student| "#{student.first_name} #{student.last_name}"}.join(',')

      table_row[:valid] = grouping.is_valid?
      table_row[:filter_valid] = grouping.is_valid?

      table_row
  end

  # Given a student and all students belonging to an assignment
  # (assignment_memberships), constructs a table row to be insterted
  # into the students FilterTable in the groups view.  Called whenever it
  # is necessary to update the students table.
  def construct_student_table_row(student, students_in_assignment)
    table_row = {}

    table_row[:id] = student.id
    table_row[:filter_table_row_contents] = render_to_string :partial => 'groups/table_row/filter_table_student_row', :locals => {:student => student}

    table_row[:user_name] = student.user_name
    table_row[:first_name] = student.first_name
    table_row[:last_name] = student.last_name
    table_row[:filter_student_assigned] = students_in_assignment.include?(student)

    table_row
end
end

app/views/groups/_delete_errors.html.erb
<ul>
  <% group_names.each do |group_name| %>
    <li><%= group_name %></li>
  <% end %>
</ul>

app/views/groups/_join.html.erb
<%= form_tag :controller => 'groups', :action => 'join', :id => @assignment.id do %>
  <p>
    <b><%= @group.inviter.user_name %></b> has invited you to join his group
    for assignment <b><%= sanitize(@assignment.short_identifier) %></b>.
  </p>

  <p>Would you like to accept this invitation?</p>

  <%= submit_tag "Accept", :name => 'accept' %>
  <%= submit_tag "Reject", :name => 'reject',
    :confirm => "Are you sure? This will make you create your own group" %>
<% end -%>

app/views/groups/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'manage_groups.js',
                             'FilterTable/FilterTable.js',
                             'Groups/tabs_boot.js',
                             'Groups/index' %>

  <%= render :partial => 'layouts/head' %>

  <%= render :partial => "boot", :formats => [:js], :handlers => [:erb] %>

  <script type="text/javascript">
  //<![CDATA[

  var modalCreate = null;
  var modalAssignmentGroupReUse = null;
  var modalAddMember = null;
  var modalNotesGroup = null;

  function make_new_group() {
    if (<%= @assignment.group_name_autogenerated %>)
    {
        new Ajax.Request('<%= new_assignment_group_path(@assignment)%>',
                {
                    asynchronous:true,
                    evalScripts:true,
                    method:'get',
                    parameters: 'authenticity_token=' + AUTH_TOKEN
                })

    }
    else
    {
        modalCreate.open();
        $('new_group_name').setValue('');
        return false;
    }
  }

  function submit_new_group(new_group_name) {

    //close the dialog
    modalCreate.close();
    //send AJAX request
    new Ajax.Request('<%= new_assignment_group_path(@assignment)%>',
                     {
                        asynchronous:true,
                        evalScripts:true,
                        method:'get',
                        parameters:'&new_group_name=' + new_group_name +
                        '&authenticity_token=' + AUTH_TOKEN
                      })
  }

  function assignment_group_use() {
      modalAssignmentGroupReUse.open();
      $('clone_groups_assignment_id').setValue('');
      return false;
   }

  function submit_assignment_group_use(clone_groups_assignment_id) {

    // close the dialog
    modalAssignmentGroupReUse.close();

    // send AJAX request
    new Ajax.Request('<%= use_another_assignment_groups_assignment_groups_path(@assignment)%> ',
                      {
                        asynchronous:true,
                        evalScripts:true,
                        parameters:'&clone_groups_assignment_id=' + clone_groups_assignment_id
                          + '&authenticity_token=' + AUTH_TOKEN
                      })
  }

  document.observe("dom:loaded", function() {
    modalCreate = new Control.Modal($('create_group_dialog'),
    {
      overlayOpacity: 0.75,
      className: 'modalCreate',
      fade:false
    });

    modalNotesGroup = new Control.Modal($('notes_dialog'),
    {
      overlayOpacity: 0.75,
      className: 'modalNotesGroup',
      fade:false
    });

    modalAssignmentGroupReUse = new Control.Modal($('assignment_group_use_dialog'),
    {
      overlayOpacity: 0.75,
      className: 'modalAssignmentGroupReUse',
      fade:false
    });

    // set up event handlers to show the loading spinner while
    // an ajax call us working
    $("global_action_form").observe('ajax:after', function(evt, status, data, xhr) {
      thinking();
    });

    $("global_action_form").observe('ajax:success', function(evt, status, data, xhr) {
      done_thinking();
    });

  });

  //]]>
  </script>
<% end %>


<% if @assignment.past_due_date? %>
<div class="notice">
  <%=t('groups.editing_past_due_date_warning')%>
</div>
<% end %>

<div id="title_bar">
  <h1><%= I18n.t("groups.manage_groups") %></h1>
  <div class="colRightGroups">
      <div class="headingButtons  ">
      <%  # Allow cloning groups forward only if its web submits are disallowed
          # for this assignment.
          if !@assignment.allow_web_submits %>
        <%= button_to_function t("groups.another_assignment_group"),
          'assignment_group_use(); return false;', :class => "button" %>
        <span class="menu_bar">|</span>
      <% end %>
      <%= button_to_function I18n.t('download'), 'modal_download.open();' %>
      <span class="menu_bar">|</span>
      <%= button_to_function I18n.t('upload'), 'modal_upload.open();' %>
    </div> <!-- rightjustify-->
  </div> <!-- colrightgroups-->

  </div> <!-- title_bar-->


<div class="wrapLeft">
</div>

<div class="clear"></div>

<div id="notice">
    <div class="success" id="add_success" style="display: none; ">
            </div>
  <% # This is for error display injected by JavaScript
   %>

  <div class="error" id="errors" style="display: none; ">
    <h3><%= t("groups.problem") %></h3>
    <div id="errors_title">
    </div>
    <div id="errors_contents">
    </div>
  </div>

  <div class="warning" id="warnings_group" style="display: none; ">
    <h3><%= t("groups.warning") %></h3>
    <div id="warnings_group_msg">
    </div>
  </div>

  <div class="warning" id="warnings_grace" style="display: none; ">
    <h3><%= t("groups.warning") %></h3>
    <div id="warnings_grace_msg">
    </div>
  </div>
 <div class="warning" id="global_action_warning" style="display: none; ">
	<h3><%= t("groups.warning") %></h3>
	<div id="global_action_warning_msg">
	</div>
  </div>

  <% # all other flash messages %>
  <%= render 'shared/flash_message' %>
</div><!-- Notice -->



<%= form_tag global_actions_assignment_groups_path(@assignment),
             :id => "global_action_form",
             :remote => true do %>


<div class="clear"></div>
<div class="colsLeftHeavy">
  <div class="colRightGroups">
    <div class="wrapRightGroups">
      <div class="pane">
        <span id="loading_list">
          <%= image_tag("spinner.gif") %><%= t("groups.loading_list") %></span>
        <ul id="groups_tabs"class="subsection_tabs">
          <li class="tab">
            <a href="#none" id="filter_link_none" class="filter_selected">
              <%= raw(I18n.t("groups.all_grouping_counts")) %></a></li>
          <li class="tab">
            <a href="#validated" id="filter_link_validated">
              <%= raw(I18n.t("groups.valid_grouping_counts")) %></a></li>
          <li class="tab">
            <a href="#unvalidated" id="filter_link_unvalidated">
              <%= raw(I18n.t("groups.not_valid_grouping_counts")) %></a></li>
          <li class="button_tab">

          </li>
        </ul>
        <div id="none"></div>
        <div id="validated"></div>
        <div id="unvalidated"></div>

        <div class="clear"></div>
        <div id="groups_container" class="tabbedArea">
          <%= label_tag 'search_groupings', "Search:", :class => 'bold_inline_label'%>
          <%= text_field_tag 'search_groupings', nil,
            :onkeyup => "groupings_table.add_filter('search'); groupings_table.render();",
            :onkeypress => "stop_submit(event);"%>
          <%= button_to_function t('groups.add_new'), "make_new_group()" %>
          <div class="globalActionIconsTop">
            <%= image_submit_tag "icons/tick.png",
              :class =>'image_input',
              :title => I18n.t("groups.action.validate"),
              :alt => I18n.t("groups.action.validate"),
              :onclick => "$('global_actions').setValue('valid');" %>
            <%= image_submit_tag "icons/cross.png",
              :class =>'image_input',
              :title => I18n.t("groups.action.invalidate"),
              :alt => I18n.t("groups.action.invalidate"),
              :onclick => "$('global_actions').setValue('invalid');" %>
            <%= image_submit_tag "icons/bin_closed.png",
              :class =>'image_input', :title => I18n.t("groups.action.delete"),
              :alt => I18n.t("groups.action.delete"),
              :onclick => "$('global_actions').setValue('delete');" %>
          </div>
          <table class="groups" id="groups">
          </table>
          <%= hidden_field_tag 'submit_type', 'global_action', :id => 'submit_type' %>
          <%= hidden_field_tag 'global_actions'%>
          <div class="globalActionIconsBottom">
            <%= image_submit_tag "icons/tick.png",
              :class =>'image_input',
              :title => I18n.t("groups.action.validate"),
              :alt => I18n.t("groups.action.validate"),
              :onclick => "$('global_actions').setValue('valid');" %>
            <%= image_submit_tag "icons/cross.png",
              :class =>'image_input',
              :title => I18n.t("groups.action.invalidate"),
              :alt => I18n.t("groups.action.invalidate"),
              :onclick => "$('global_actions').setValue('invalid');" %>
            <%= image_submit_tag "icons/bin_closed.png",
              :class =>'image_input',
              :title => I18n.t("groups.action.delete"),
              :alt => I18n.t("groups.action.delete"),
              :onclick => "$('global_actions').setValue('delete');" %>
          </div>
        </div><!-- group container -->
      </div>
    </div>
  </div> <!-- colRightGroups -->

  <div class="colLeftGroups">
    <% # order of processing students is important. we go through each member
       # one by one and delete them above from the list of students
       # if they are already in a group
       # See manage/_group.html.erb
    %>
    <div class="wrapLeftGroups">
      <div class="pane">
        <span id="loading_students_list">
          <%= image_tag("spinner.gif") %><%= t("groups.loading_list") %></span>
        <ul id="students_tabs" class="subsection_tabs">
          <li class="tab">
            <a href="#students_none" id="filter_link_students_none">
              <%= raw(I18n.t("groups.all_students")) %></a></li>
          <li class="tab">
            <a href="#unassigned" id="filter_link_students_unassigned" class="filter_selected">
              <%= raw(I18n.t("groups.unassigned_students")) %></a></li>
          <li class="tab"><a href="#assigned" id="filter_link_students_assigned">
            <%= raw(I18n.t("groups.assigned_students")) %></a></li>
        </ul>

        <div id="students_none"></div>
        <div id="unassigned"></div>
        <div id="assigned"></div>

        <div class="tabbedArea">
          <div class="searchBox">
            <%= label_tag 'search_students', "Search:",
              :class => 'bold_inline_label'%>
            <%= text_field_tag 'search_students', nil,
               :onkeyup => "students_table.add_filter('search'); students_table.render();",
               :onkeypress => "stop_submit(event);" %>
          </div>
          <table class="students" id="students">
          </table>
        </div>

      </div>
    </div>
  </div> <!-- colLeftGroups -->

  <div id="centreColumn" class="centreColumn">
      <%= image_submit_tag "add_arrow.png",
        :onclick => "$('global_actions').setValue('assign');",
        :alt => I18n.t('add_members'),
        :class =>'image_input',
        :title => I18n.t('add_members') %>
      <br/><br/>
      <%= image_submit_tag "remove_arrow.png",
        :onclick => "$('global_actions').setValue('unassign');",
        :alt => I18n.t('remove_members'),
        :title => I18n.t('remove_members'),
        :class =>'image_input' %>
  </div>

</div> <!-- ColsLeftHeavy -->
<% end %> <!-- remote form tag -->

<!-- Modal Windows -->



<div id="assignment_group_use_dialog">
  <h2><%= I18n.t("groups.reuse_groups") %></h2>
  <fieldset>
  <p><%= I18n.t("groups.assignment_to_use") %></p>
  <select id="clone_groups_assignment_id" name="clone_groups_assignment_id">
    <% @all_assignments.each do |an_assignment| %>
      <% if an_assignment != @assignment && an_assignment.allow_web_submits == false %>
        <option value="<%=(an_assignment.id)%>"><%=(an_assignment.short_identifier)%></option>
      <% end %>
    <% end %>
  </select>
  </fieldset>
  <p class="p_modal">
    <%= button_to_function t(:submit),
     "if (confirm(\"#{I18n.t('groups.delete_groups_linked')}\")) submit_assignment_group_use(escape($F('clone_groups_assignment_id')))" %>
    <%= button_to_function t(:cancel), 'modalAssignmentGroupReUse.close()'%>
  </p>
</div> <!-- Assignement reuse groups modal-->

<div id="create_group_dialog">
  <h2><%= I18n.t("groups.create_new_group") %></h2>
  <fieldset>
  <%= I18n.t("groups.groupe_name") %>
  <input type="text" maxlength="30" id="new_group_name"></input>
  </fieldset>
  <p class="p_modal">
    <%= button_to_function I18n.t("groups.create_new_group"),
  "submit_new_group(escape($F('new_group_name')));" %>
    <%= button_to_function t(:cancel), 'modalCreate.close()'%>
  </p>

</div>

<div id="rename_group_dialog">
</div>

<div id="notes_dialog">
</div>

<div id="download_dialog">
  <h2><%= I18n.t("groups.download.download_groups_file") %></h2>
  <%= link_to t('groups.download.download_csv'),
              { :controller => 'groups', :action => 'download_grouplist',
                :id => @assignment.id },
              :onclick => 'modal_download.close();' %>
  <br />
  <br />
  <%= button_to_function I18n.t('cancel'),
                         'modal_download.close(); return false;' %>
</div>

<div id="upload_dialog">
  <h2><%= I18n.t("groups.upload.upload_groups_file") %></h2>
  <p>
    <%= I18n.t("groups.upload.description").html_safe %>
    <% if !@assignment.groupings.nil? && @assignment.groupings.length > 0 %>
      <br/>
      <div class="information">
        <%= I18n.t("groups.upload.importing") %>
      </div>
    <% end %>
  </p>
  <%= form_for :group, :html => {:multipart => true},
                       :url => { :controller=>"groups",
                               :action => 'csv_upload',
                               :id => @assignment.id } do |f| %>
  <p>
    <%= I18n.t("encoding") %>
    <%= select_tag(:encoding, options_for_select(@encodings)) %>
    <br />
    <br />
    <%= f.file_field :grouplist, :size => 2 %> <br />
    <%= submit_tag t(:upload), :disable_with => t(:uploading_please_wait) %>
    <%= button_to_function I18n.t('cancel'),
                           'modal_upload.close(); return false;' %>
  </p>
  <% end %>
</div>